### ISSUE TITLE
Implement login kind discovery and flow initiation/completion

### ISSUE THREAD

**Issue by JamesPrice76** [flathub/frontend#163]

**Comment by kymckay** [comment]
- Login flow will make use of API specified by https://github.com/flathub/backend/issues/94
- Flow can't be fully implemented until https://github.com/flathub/backend/issues/95 is done

**Comment by kymckay** [comment]
Before I log off for that day, working on frontend login flow, the error I'm getting is at the 2nd stage of our API where I'm asking for the redirect URI:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/auth/login/github. (Reason: CORS header 'Access-Control-Allow-Origin' missing). 

I see two options:
1. I'm currently fetching this in an onClick handler client-side, I could move the fetching to serverSideProps (i.e. data is fetched server side on each page load), but I foresee that this could be problematic on the user end if there's client-side caching or weird user behaviour resulting in a link being used, then shown again and now invalid. This would also waste server cycles getting the redirect URL for all providers every time the page loads.
2. Edit the server to allow access from the frontend (my knowledge of CORS stuff is minimal so this may be the wrong interpretation).
