### ISSUE TITLE
Get rid of editors game picks

### ISSUE THREAD

**Issue by razzeee** [flathub/frontend#171]
The people over in the gnome design matrix channel suggested, that the editors game picks are probably an unnecessary burden.

1. Let's merge them with the normal picks
2. It will be hard enough to keep these updated, we should do another set of apps each month I think
3. Let's only list 6 apps and remove the show more button 
3. Should also make it easier to find enough nice things

I'm not completely happy with the `Editor's Choice Apps` naming. I think I thought of something better, but forgot it...

**Comment by nedrichards** [comment]
I'm not certain that those people are correct - games historically are the most popular part of flathub and ensuring that we suggest high quality ones at the top level is important for adoption and usage. Let's evaluate this a little more - although I'm not against having a mixed area so long as there's plenty of game representation.

**Comment by razzeee** [comment]
The real problem I think is, that it needs to live and be maintained. So picking new apps each month shouldn't be a chore and actually never pushed to the side/forgotten. And that should be way easier with not as many apps.

**Comment by nedrichards** [comment]
It does, but keeping things 'fresh' is less important than it might seem - a supposition might be the average user of the flathub website does not continue to do all their installing from the site. The intention being to get their *first* app installed and then subsequent installs and updates primarily take place in an on device software store.

That being said - it's a good point about making it easier to perform a curatorial workflow. For example we could think of a way of more easily connecting the app approval process to a candidate list, or thinking about how to connect more to the new developer experience we're creating.

**Comment by razzeee** [comment]
I think they now feel pretty okay, with the order changing up from time to time. Having a process attached to how they get changed would be nice, but as that should probably be connected to the approval workflow, I don't think this is the right repo to talk about it.
