### ISSUE TITLE
tweak "show more" copy since it won't always show more

### ISSUE THREAD

**Issue by nedrichards** [flathub/frontend#173]
we should change the 'show more' copy on the developer apps carousel to make it clearer that it's linking to a developer's catalog page since it won't always 'show more' apps unless the developer has >6 apps.

**Comment by razzeee** [comment]
So should we show it at all? Easiest would be hiding it.

https://github.com/razzeee/frontend/commit/a7cc6350b7f09b095e4a355b3202a3b1c8cf7591

If we want to go the other way, it might be interesting how to communicate this clearly.

**Comment by nedrichards** [comment]
We should help developers discover the link - this developer specific landing page has been a long term request of big app providers such as KDE otherwise yes, I'd have said only show if apps>6. I will have a think about some better copy. I like your initial change though, make it better first!

**Comment by razzeee** [comment]
Yes, but that should be adressed in a different issue. At least parts of this will happen with the current contract and when we have dev logins, I'm happy to work on a statistics page.

**Comment by nedrichards** [comment]
To clarify, a developer specific landing page in this context is the developer collection page here https://flathub.vercel.app/apps/collection/developer/The%20GNOME%20Project helping developers find this so they can link to it on their site would be helpful.

**Comment by razzeee** [comment]
Ah right, that sounds like two usecases, I meant something different above so nvm.

**Comment by razzeee** [comment]
Landed the hiding of the button, if there are not more then 6 apps
