### ISSUE TITLE
Animation or confirmation for copy action

### ISSUE THREAD

**Issue by nedrichards** [flathub/frontend#181]
It would be nice to have a little tick animation or similar confirmation after pressing the copy action on the manual install action on the item page. It currently feels a little floaty. For an example of how this can feel nicer see the copy action on github itself whilst copying a URL for a build (which is of course the exact same action):

https://github.com/flathub/flathub/pull/2814#issuecomment-1025392159

**Comment by razzeee** [comment]
There is a small activation response, but it's not very obvious.

**Comment by razzeee** [comment]
https://github.com/flathub/frontend/commit/579639734430a2cd2ac7b42eda3831dcb118c48e is a step in that direction

**Comment by razzeee** [comment]
Closing for now as it has been merged and we can always keep improving animations
