### ISSUE TITLE
Support Additional Categories

### ISSUE THREAD

**Issue by JakobDev** [flathub/frontend#189]
The new Frontend currently only allows browsing by Main Categories, but not by [Additional Categories](https://specifications.freedesktop.org/menu-spec/latest/apas02.html). So it's currently only possible e.g. to view all games, but not all Emulators, which is a Subcategory of games. Someone who is looking for Emulator is not interested in other games. Same for a Person looking for WebBrowser or TextEditor.

**Comment by razzeee** [comment]
These kind of queries should probably be just searched for. AFAIK the search should have the needed data for this. As long as apps have decent descr'and summaries.

**Comment by nedrichards** [comment]
Yeah, the menu spec is sadly frozen in time and exposing all of that is absolutely not relevant. I'd for sure be interested in seeing how people browse, search and discover but I don't think that specific encoded structure is a general win.

**Comment by razzeee** [comment]
We do have some matomo improvements with the new page, especially around search.

**Comment by razzeee** [comment]
Btw, the search for emulator seems quiet okay for me https://beta.flathub.org/apps/search/emulator?page=1

**Comment by razzeee** [comment]
I'll close this for now, feel free to reopen it, if you think it's needed.
