### ISSUE TITLE
"WHOOPS" on userpage due to app without appstream

### ISSUE THREAD

**Issue by wjt** [flathub/frontend#227]
After logging into https://beta.flathub.org/, on https://beta.flathub.org/userpage I see:

> **WHOOPS**
>
> An error occurred on the client.
>
>You might want to retry or go back [home](https://beta.flathub.org/).

In the browser console I see:

```
Access to font at 'https://dl.flathub.org/repo/assets/Inter-3.19/Inter-Regular.woff2' from origin 'https://beta.flathub.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

(Unrelated)

```
flathub.org/api/v2/appstream/org.flathub.flatpak-external-data-checker:1          Failed to load resource: the server responded with a status of 404 ()
```

I believe this is the problem. I comaintain https://github.com/flathub/org.flathub.flatpak-external-data-checker. This is a CLI tool and, for better or for worse, it has no appstream and sets the flag in `flathub.json` to suppress the build-time check for it.

Then:

```
framework-5f4595e5518b5600.js:1 TypeError: Cannot read properties of null (reading 'id')
    at _next/static/chunks/pages/apps/collection/popular-ff792a589054bf0e.js:1:4075
    at Array.map (<anonymous>)
    at d (_next/static/chunks/pages/apps/collection/popular-ff792a589054bf0e.js:1:4020)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Ku (framework-5f4595e5518b5600.js:1:111712)
    at Li (framework-5f4595e5518b5600.js:1:98953)
    at Ni (framework-5f4595e5518b5600.js:1:98881)
    at Pi (framework-5f4595e5518b5600.js:1:98744)
    at bi (framework-5f4595e5518b5600.js:1:95710)
    at framework-5f4595e5518b5600.js:1:45204
cu @ framework-5f4595e5518b5600.js:1
main-b4170979ca4ef2ba.js:1 TypeError: Cannot read properties of null (reading 'id')
    at _next/static/chunks/pages/apps/collection/popular-ff792a589054bf0e.js:1:4075
    at Array.map (<anonymous>)
    at d (_next/static/chunks/pages/apps/collection/popular-ff792a589054bf0e.js:1:4020)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Ku (framework-5f4595e5518b5600.js:1:111712)
    at Li (framework-5f4595e5518b5600.js:1:98953)
    at Ni (framework-5f4595e5518b5600.js:1:98881)
    at Pi (framework-5f4595e5518b5600.js:1:98744)
    at bi (framework-5f4595e5518b5600.js:1:95710)
    at framework-5f4595e5518b5600.js:1:45204
ye @ main-b4170979ca4ef2ba.js:1
main-b4170979ca4ef2ba.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ye @ main-b4170979ca4ef2ba.js:1
```

**Comment by razzeee** [comment]
This should be fixed, when https://github.com/flathub/backend/pull/135 is merged

**Comment by razzeee** [comment]
Can you try again?

**Comment by wjt** [comment]
It works!

I don't see anything for org.flathub.flatpak-external-data-checker, which I presume is still because it has no appdata (and I see a 404 in the console). I guess that is a separate, wishlist issue.

**Comment by razzeee** [comment]
It does have some app data, but it's probably missing stuff like icons etc.
Which endpoint gives a 404?

Will Thompson ***@***.***> schrieb am Di., 1. März 2022,
10:26:

**Comment by wjt** [comment]
GET https://beta.flathub.org/_next/data/9kL2LAKaCB7Mddy6EwcP0/apps/details/org.flathub.flatpak-external-data-checker.json 404

**Comment by razzeee** [comment]
Yeah, that's trying to access the detail page for it (probably preloading) but we only build those for desktop apps right now.

**Comment by razzeee** [comment]
@wjt  check again please
