### ISSUE TITLE
Setup a translation workflow

### ISSUE THREAD

**Issue by razzeee** [flathub/frontend#240]
- [x] Get something like weblate going
- [x] Configure it to get/push to this repo
- [x] Add weblate to README

**Comment by neilmcgovern** [comment]
Please check in advance whether your project is eligible for gratis project hosting on this site.
- Translated content has to be released under a license approved by OSI or recognized as libre by FSF.
- All the source code has to be publicly available in a supported version control system.
- Translations have to be in the same repository as the source code, or under the same project/organization as the source code repository.
- Using Weblate has been approved by the upstream project.
- Mention you use Weblate for translations in the README. It’ll attract new translators and also help Weblate to be free for more projects.
- The project has had active development for at least three months.
- You will have 14 days to set up your project.
- Please request project approval once you finish the setup.
- Unapproved projects will be removed.
- There is no guarantee of service availability, nor quality for free service plan.

**Comment by razzeee** [comment]
I think that mean, we need to add them to the readme, the other things should be fine from my POV

**Comment by razzeee** [comment]
We should be good now, as of https://github.com/flathub/frontend/pull/262 from my POV.

Will you double check @neilmcgovern and push the button?

**Comment by neilmcgovern** [comment]
Magic button pressed, will update here when we get the result.

**Comment by neilmcgovern** [comment]
This is now confimed, so closing this issue
