### ISSUE TITLE
Error is shown in button

### ISSUE THREAD

**Issue by razzeee** [flathub/frontend#241]
![image](https://user-images.githubusercontent.com/5943908/156825959-72201e9f-3294-49f4-96de-c401125982ab.png)

@kymckay

**Comment by kymckay** [comment]
Thanks for opening this, easy to change to show below the button if that's all we need short-term. 

However, for longer-term, on my personal wishlist of follow up tasks is to improve everywhere feedback messages are possible. I was thinking of something like:

- Update the feedback component for use as a more generic system, such as showing dismissible messages on top of the page (absolute container with sticky message) over to the side. This would make UX more consistent and the component more easily reusable to make development easier (not having to consider the page layout when showing an error). The main downside I see would be that the error is no longer clearly associated with an element by proximity, but I think that can be alleviated if the message clearly identifies the action responsible.

@razzeee Does that sound sensible to you / do you envision another solution?

**Comment by razzeee** [comment]
Yeah, I would also go for toasts here, probably something like https://www.npmjs.com/package/react-toastify
