### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by barthalion** [flathub/frontend#248]
Turns out we missed adding a LICENSE file to the project, and now we need to ask all contributors for consent to (re)license it. The traditional license used by Flathub infrastructure projects is `Apache-2.0`. Please confirm you are okay with applying that license.

- [x] @razzeee 
- [x] @bilelmoussaoui 
- [x] @kymckay 
- [x] @jhorbowicz 
- [x] @barthalion

**Comment by barthalion** [comment]
I agree to license my commits under the Apache-2.0 license.

**Comment by bilelmoussaoui** [comment]
ack

**Comment by kymckay** [comment]
I agree to license my commits under the Apache-2.0 license.

**Comment by razzeee** [comment]
I agree to license my commits under the Apache-2.0 license.

**Comment by jhorbowicz** [comment]
I agree to license my commits under the Apache-2.0 license.
