### ISSUE TITLE
Description and changelog content dissappear on page refresh or direct page access

### ISSUE THREAD

**Issue by g-fb** [flathub/frontend#274]
When opening an app page (https://beta.flathub.org/apps/details/org.kde.haruna) from another page (home, search or other listing) the page looks fine.
But if I refresh the page or try to access it directly the content of the description and changelog sections are removed (they do load for a brief moment).

**Comment by razzeee** [comment]
Oh yeah, will check that. Thought it only happens in dev mode :/
