### ISSUE TITLE
Improve the styling

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/frontend#4]
The whole thing needs some CSS refinement to make sure things are looking pretty!

cc @bertob

**Comment by bertob** [comment]
Yup, it's on my list!

**Comment by bilelmoussaoui** [comment]
![image](https://user-images.githubusercontent.com/7660997/115073590-d6567380-9ef8-11eb-8c4f-9658287b13d3.png)


cc @jhorbowicz, this is part of Tobias's redesign of the frontend, we should try to implement it. There are some missing pages for now, but those can be handled later in the future

**Comment by jhorbowicz** [comment]
Hi @bilelmoussaoui, thanks for update, I saw, that part of it is already implemented.

From what I discussed with @barthalion the main focus right now is to publish flathub on `next.js` that will use the new API. In that case I think it could be valuable to stick to something between old and new design, but something that will be consistent, of course.

In #7, I copied styles that you implemented earlier to `new-styles` directory that is not used for now and tried to follow the convention in naming of classes that you proposed, so once we will have new designs ready, we can easily switch to use it.

I also have some doubts if that redesign would make using flathub easier and more friendly. It looks much like an native `Gnome Software` app (I know that it was meant too look like that ;) ) and I would say, that web applications went into little bit different direction. Maybe we could start with publishing old design for now, and once new will be implemented we could let community tell us, which one is better for them :)

Of course I am only contributor here, so I will follow any decision :)

**Comment by bilelmoussaoui** [comment]
Sounds good to me, there's no need to rush implementing the mockups as they are not complete yet, as you can see there's only the main page.

But there are definitely a bunch of stuff we could borrow from the new mockups such as the number of applications displayed per section on the homepage for example.

**Comment by razzeee** [comment]
Should I ask around to see if I can find a designer willing to mock something up?

**Comment by barthalion** [comment]
Sounds great, yes. The new design of GNOME Software looks great for a desktop app but I don't think it really fits how websites are designed.

**Comment by razzeee** [comment]
I think it would work fine for a website, but it's positioning flathub too much in the gnome camp.

**Comment by barthalion** [comment]
Yes, that's a fair point as well. It's not a GNOME-specific project by any means.

**Comment by razzeee** [comment]
I think we can close this for now and proceed in other issues. Feel free to ping or reopen, if you think different.
