### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by jhorbowicz** [flathub/frontend#42]
We have only the basic readme. It is not helpful at all for people who would potentially like to contribute.

**Comment by razzeee** [comment]
I've proposed a MR for this.

**Comment by jhorbowicz** [comment]
> Can we consider rolling the backend and frontend into one git repo? Is there any value added by keeping them apart?

Could you elaborate on that? What problems would it solve? I don't see any, to be honest. Those are completely independent apps, that are written in different stacks and by different people. Unless there are some really good arguments for that, or others have different opinion on that, I would avoid keeping it in one repository.

**Comment by razzeee** [comment]
From my POV, keeping them separate only makes sense, if there are more consumers. So not only this frontend.

It would improve:
- Dev Setup (essentially makes the readme shorter)
- History (ideally you'll implement frontend and backend in tandem in the same PR/commits)
- Confusion on which backend is the correct one this frontend uses
- And also makes it more natural, to open this in one editor (but you could have done that before)
