### ISSUE TITLE
Side menu in collections and categories

### ISSUE THREAD

**Issue by jhorbowicz** [flathub/frontend#43]
We are currently missing side menu that should be visible on the left of collections and categories. On smaller screens (only smartphones) it should be replaced by burger menu. After clicking it appears on left side of the screen,
![Screenshot from 2021-10-26 22-38-59](https://user-images.githubusercontent.com/23322970/138957374-558c36da-e65c-4284-8658-ca0cc2977bcf.png)
![Screenshot from 2021-10-26 22-39-30](https://user-images.githubusercontent.com/23322970/138957452-c2a6d2ae-81aa-4c2f-a8a8-af427bc66f97.png)

**Comment by razzeee** [comment]
I went ahead with the simplification I pitched. Closing for now.
