### ISSUE TITLE
Clearly show the architecture the package is available for

### ISSUE THREAD

**Issue by klem-everywhere** [flathub/frontend#47]
Issue: https://github.com/flathub/linux-store-frontend/issues/263
I don't see it in the details page from the source code.

Today, there is still confusion when users try to install packages that are not available for their architecture. It is usually Chromebook users (arm or aarch64 platform) for packages that are Intel only and all they get is a "package not found" error.

The details page should display:

- architecture the package is available for
- a clear mention that the package might not be available for architecture the user runs (by checking the User-Agent)

**Comment by razzeee** [comment]
I've implemented the first part 
![image](https://user-images.githubusercontent.com/5943908/141874484-4a4701df-81a1-49c4-8c9a-aa8a68201404.png)

It's part of  https://github.com/flathub/frontend/pull/63
If you have any ideas on how to make it clearer and potentially remove the jargon, please let me know.

**Comment by klem-everywhere** [comment]
> I've implemented the first part ![image](https://user-images.githubusercontent.com/5943908/141874484-4a4701df-81a1-49c4-8c9a-aa8a68201404.png)
> 
> It's part of #63 If you have any ideas on how to make it clearer and potentially remove the jargon, please let me know.

Oh this looks great!

**Comment by razzeee** [comment]
Looking for a library to parse the UA, turns up this https://faisalman.github.io/ua-parser-js/ but it doesn't seem like Firefox sets the arch on android. Will have to check other platforms.

**Comment by razzeee** [comment]
It's set on linux, but we would need a mapping table and that's going to be a pain to figure out and maintain. I would prefer to leave it like this. But feel free to reopen this.
