### ISSUE TITLE
Setup a staging server

### ISSUE THREAD

**Issue by razzeee** [flathub/frontend#62]
It would be nice to host the current dev build online. This would also need the backend to be running somewhere.

Might also help with testing the tracking setup, as it might fail due to being run on localhost.

**Comment by razzeee** [comment]
It seems like vercel/nextjs doesn't really support this, at least judging on the docs.

We also tested the tracking successfully on localhost

**Comment by razzeee** [comment]
It seems like I missed https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables as it's a bit weirdly structured in the docs.

**Comment by nedrichards** [comment]
What do we actually need here @barthalion to get this on 'production equivalent' flathub infra?

**Comment by barthalion** [comment]
This is on my list for "soon", I need to do some Dockerfile changes. I hope to get it done this week.

**Comment by razzeee** [comment]
https://beta.flathub.org/ is a thing now
